### ISSUE TITLE
RangeError for big int

### ISSUE THREAD

**Issue by ChrisMarxDev** [simolus3/web3dart#101]
I have a Solidity Function that looks something like the following:
```
function checkState(address publicKey)
        public
        view
        returns (string memory, uint256)
    {
        Entry memory entry = entries[publicKey];
        uint256 result = entry.timestamp + immunityPeriod;
        return (entry.idHash, result);
    }

```
I recently added the uint256 as return parameter. The parameter represents a timestamp.
The result in the truffle console looks like : `{ '0': 'abcd', '1': <BN: 608c0af1> }`

However after setting the correct abi-file if I now call the altered function with web3dart, I get the following error.

Unhandled Exception: RangeError: Value not in range: 18813707208
```
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:4791:5)
#1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1931:5)
#2      DynamicBytes.decode (package:web3dart/src/contracts/abi/arrays.dart:92:14)
#3      StringType.decode (package:web3dart/src/contracts/abi/arrays.dart:122:46)
#4      TupleType.decode (package:web3dart/src/contracts/abi/tuple.dart:98:33)
#5      TupleType.decode (package:web3dart/src/contracts/abi/tuple.dart:98:33)
#6      ContractFunction.decodeReturnValues (package:web3dart/src/contracts/abi/abi.dart:257:30)
#7      Web3Client.call (package:web3dart/src/core/client.dart:328:21)


```
I call the contract like the following: 

` List<dynamic> result = await query("checkState", [target]);`

```
  Future<List<dynamic>> query(String functionName, List<dynamic> args) async {
    final contract = await loadContract();
    final ethFunction = contract.function(functionName);
    final data = await ethClient.call(
        contract: contract, function: ethFunction, params: args);
    return data;
  }
```

Is there anything I have to change in my code to fix this or is this something framework related? 

I am using the following version web3dart: ^2.0.0-dev.6

When I edited the contract for testing purposes to return a int256 and just put the number 1 as return value. The contract call worked and returned the correct results.

**Comment by simolus3** [comment]
Do you have access to the raw hex encoding that `web3dart` fails to decode?

**Comment by ChrisMarxDev** [comment]
I tried to recreate it today to get the raw hex encoding and for some weird reason I am not getting the error anymore. I will monitor this behaviour and if the error occurs again, I will notice you and post the hex encoding. 
Still thank you very much for your attention.
