### ISSUE TITLE
cannot open file abi.json.

### ISSUE THREAD

**Issue by mundhrakeshav** [simolus3/web3dart#103]
![Screenshot from 2020-06-01 12-32-40](https://user-images.githubusercontent.com/55694394/83384336-b2835f80-a404-11ea-8d65-c3761ee71d8b.png)
i placed my file in lib folder and changed location like this
final File abiFile = File(join(dirname(Platform.script.path),' lib ', 'abi.json'));
neither does it works when place it in my project folder.

**Comment by simolus3** [comment]
That doesn't work with Flutter, only with standalone Dart. You could either place the json in a Dart string constant or make it an [asset](https://flutter.dev/docs/development/ui/assets-and-images) that you could load.
