### ISSUE TITLE
RPCError: got code -32010

### ISSUE THREAD

**Issue by AmrAhmedA** [simolus3/web3dart#110]
I'm trying to send a transaction to a deployed contract on Kovan Test network through Infura API.

```
      await client.sendTransaction(
        credentials,
        Transaction.callContract(
          contract: contract,
          function: voteFunction,
          parameters: [BigInt.from(selectedVoterId)],
        ),
      );
```
When I try to call the function through a raised button it displays the following error in the console command
```
RPC Error: get code -32010 with msg "Transaction with the same hash was already imported.".'
```
When I tried to call the function for once more, it displays the following error
```
RPCError: got code -32010 with msg "Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.".
```
I have imported the ABI successfully and I did call some of the functions from the contract successfully. but when It comes to signing transactions, I stumble. 
and how to check if the transaction succeeded or not?
Thanks in advance

**Comment by simolus3** [comment]
This might happen if you sent multiple transactions in quick succession, before others were mined:

- `Transaction with the same hash was already imported.`: Sounds like you're sending the exact transaction more than once
- `Transaction gas price supplied is too low`: This indicates that you're re-using a `nonce`

Ethereum transactions have a `nonce` so that the same transaction cannot be applied multiple times. Basically, you need to increment it for each transaction you send. `Web3Dart` attempts to do this automatically, but it can only respect transactions already sent. You could use

```dart
      await client.sendTransaction(
        credentials,
        Transaction.callContract(
          contract: contract,
          function: voteFunction,
          parameters: [BigInt.from(selectedVoterId)],
          nonce: await client.getTransactionCount(yourSenderAddress, atBlock: BlockNum.pending),
        ),
      );
```

But `Web3Dart` should probably use `pending` by default...

**Comment by AmrAhmedA** [comment]
Thanks for your reply, I appreciate it, 
I'm having a problem sending and signing the first transaction. it appears I was trying to send multiple transactions but non were being mined or approved, I have cleaned flutter and tried to build the application with some modifications and still, I'm getting the same exact problem.
the function I'm trying to call in solidity is trying to do the following functionality

```solidity 
    event votedEvent(uint256 indexed _candidateId);
    function vote(uint256 _candidateId) public {
        require(!voters[msg.sender].voted, "User has voted before");

        require(
            voters[msg.sender].authorized == true,
            "User is not eligable to participate in the voting process"
        );

        require(
            _candidateId > 0 && _candidateId <= candidatesCount,
            "Candidate selection is invalid"
        );

        voters[msg.sender].voted = true;

        voters[msg.sender].vote = _candidateId;

        candidates[_candidateId].voteCount++;

        totalVotes++;

        emit votedEvent(_candidateId);
    }
```
concerning nonce, I have added the snippet for the nonce part as in the following

```dart 
void voteTransaction(int selectedVoterId) async {
    /// For extracting public key from private key
    Credentials credentials = EthPrivateKey.fromHex(
        "########");
    var address = await credentials.extractAddress();
    print("Account Address: " + address.hex);

    /// Initializing web3

    var apiUrl = "########";

    var httpClient = new Client();
    var ethClient = new Web3Client(apiUrl, httpClient);

    /// For getting the current balance
    EtherAmount balance = await ethClient.getBalance(address);
    var amount = balance.getValueInUnit(EtherUnit.ether);
    print("balance before transaction: $amount");

    final EthereumAddress contractAddr =
        EthereumAddress.fromHex('########');

    String data =
        await DefaultAssetBundle.of(context).loadString("Election.json");
    final jsonResult = json.decode(data);
//    print(jsonResult);

    final client = Web3Client(apiUrl, Client());

    final contract = DeployedContract(
        ContractAbi.fromJson(
            json.encode(jsonResult['abi']), jsonResult['contractName']),
        contractAddr);

    final voteFunction = contract.function('vote');

    var nonce = await client.getTransactionCount(address);
    print('nonce: $nonce');
    try {
      var txHash = await client.sendTransaction(
        credentials,
        Transaction.callContract(
            contract: contract,
            function: voteFunction,
            parameters: [BigInt.from(selectedVoterId)],
            gasPrice:
                EtherAmount.fromUnitAndValue(EtherUnit.gwei, BigInt.from(10)),
            nonce: await client.getTransactionCount(address,
                atBlock: BlockNum.pending()),
            from: address),
        fetchChainIdFromNetworkId: true,
      );
      await Future.delayed(const Duration(seconds: 5));
      var transactionReceipt = await ethClient.getTransactionReceipt(txHash);
      print("Transaction receipt status: " +
          transactionReceipt.status.toString());
    } catch (err) {
      print(err.toString());
    }
  }
```
when I called the function for the 1st time, there is no transaction mined, it fails in getting the transaction receipt, by displaying the following error in the console command.

```
I/flutter (30038): NoSuchMethodError: The getter 'status' was called on null.
I/flutter (30038): Receiver: null
I/flutter (30038): Tried calling: status
```
when I call the function for the 2nd time, it displays the following error in the console command, because the transaction has not been mined yet and I'm trying to send another transaction with the same nonce.

```
I/flutter (10331): RPCError: got code -32010 with msg "Transaction with the same hash was already imported.".
I/flutter ( 7949): RPCError: got code -32010 with msg "Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.".
```
I did interact and signed transactions successfully with the help of Remix Ethereum and metamask without encountering errors.
I think my problem is in sending the first transaction successfully. and for some reason, I can't figure out what is the problem, despite it worked perfectly in Remix.

**Comment by simolus3** [comment]
Sorry for the slow response. `getTransactionReceipt` only works for mined transactions, it returns `null` otherwise. If you view the transaction on a Ethereum explorer, does it go through eventually?

**Comment by AmrAhmedA** [comment]
> Sorry for the slow response. `getTransactionReceipt` only works for mined transactions, it returns `null` otherwise. If you view the transaction on a Ethereum explorer, does it go through eventually?

Thanks for your response, I did actually managed to get the transaction receipt and mine the transaction successfully, It appears that the problem was in the account it's self, and I managed it out. 
One more time thanks for your response.
