### ISSUE TITLE
How to get private key as hex string?

### ISSUE THREAD

**Issue by treeder** [simolus3/web3dart#114]
Not seeing any methods to do this.

**Comment by simolus3** [comment]
You can obtain the private key as binary data through [`EthPrivateKey.privateKey`](https://pub.dev/documentation/web3dart/latest/credentials/EthPrivateKey/privateKey.html). You can then use [`bytesToHex`](https://pub.dev/documentation/web3dart/latest/crypto/bytesToHex.html) to convert that to a hexadecimal string.
