### ISSUE TITLE
ERC20 functionality - get balance, transfer

### ISSUE THREAD

**Issue by danielnordh** [simolus3/web3dart#117]
Thanks for making this library!
As a lot of Ethereum development these days deal with ERC20 tokens it would be really useful to have basic functions for that built in, like; checking balance, approving and transferring tokens etc

For example;
`Web3Client.erc20.balanceOf(tokenContract: "anERC20ContractAddress", address: "anEthereumAddress")`

With the library as it stands, what's the easiest way to;
- Get the balance of ERC20 token for and address (say DAI or USDC for example)?
- Transfer ERC20 tokens like DAI or USDC?

**Comment by simolus3** [comment]
You would have to manually invoke the contract - we have an example for that [here](https://github.com/simolus3/web3dart/blob/master/example/contracts.dart). Maybe we can have ERC20 support in the core library given how common it is.

**Comment by simolus3** [comment]
I've just published version `2.1.0` which adds the `package:web3dart/contracts/erc20.dart` library providing the functionality you described.
