### ISSUE TITLE
Error: type 'int' is not a subtype of type 'BigInt' of 'data'

### ISSUE THREAD

**Issue by KRENERGY** [simolus3/web3dart#118]
Hello,

I haven’t been for a long time using this library; and I can speak of myself as an Ethereum novice.
I have tried to figure out this issue, but with no success.

In my smartContract, the function I call with 'Transaction.callContract' expects to receive 3 parameters : 2 ‘address’ and 1 ‘uint256’.

I have tried different way of declaration to feed ‘parameters’ List but with no result.
The last of is as follow : 

‘**listOfInputs**’ is fed with 
	[ "0x3913760837e3159713E52096188F3c52BDAffa00",
    	  "0x05B7d82bfC45be5031dd090FF1343Bc18E1276aF",
       7]

Future<String> **myUIFunction**(
Web3Client ethClient, List<dynamic> **listOfInputs**) async {
 
[…] 
    List **myContractFunction_inputs** = new List();
    **AddressType** myContractFunction_input_From;
    **AddressType** myContractFunction_input_To;
    **UintType** myContractFunction_input_Rank;

    myContractFunction_inputs.insert(
        0, myContractFunction_input_From);
    myContractFunction.insert(
        0, myContractFunction_input_To);
    myContractFunction_inputs.insert(
        0, myContractFunction_input_Rank);

    myContractFunction_inputs[0] =
        EthereumAddress.fromHex(listOfInputs[0]);
    myContractFunction_inputs[1] =
        EthereumAddress.fromHex(listOfInputs[1]);
    myContractFunction_inputs[2] = listOfInputs[2];

[…]
	final result = await ethClient.sendTransaction(
      credentials,
      Transaction.callContract(
          contract: contract,
          function: ethFunction,
          parameters: **myContractFunction_inputs**),
      fetchChainIdFromNetworkId: true,
    );
    return result;

}

launching the App, I have the Error message in the Console : 
"I/flutter ( 5105): ===> Error: type 'int' is not a subtype of type 'BigInt' of 'data'"

Thanks in advance for your time and your help.

Regards,
K.

**Comment by simolus3** [comment]
In Dart 2, an `int` is only 64 bit but ints in Ethereum can be much larger (up to 256 bit). So you need to use a [`BigInt`](https://api.dart.dev/stable/2.10.4/dart-core/BigInt-class.html):

```dart
myContractFunction_inputs[2] = BigInt.from(listOfInputs[2]);
```

**Comment by KRENERGY** [comment]
Thanks your very much !!
