### ISSUE TITLE
Does web3dart support Tron?

### ISSUE THREAD

**Issue by manianrezaie** [simolus3/web3dart#120]
Hello. 
I want to start develop a tron wallet for my experience. how can i use web3dart to interact  with Tron?
or is there any other tron library available for dart?
Thanks

**Comment by simolus3** [comment]
No, this library doesn't support TRON and I'm not aware of any Dart library for it either.

It looks like tron supports EVM-contracts, so maybe you could use `package:web3dart/abi.dart` to invoke TRON contracts too. Apart from that, you'd have to write your own wrapper around their apis.
