### ISSUE TITLE
RPCError - invalid sender when using sendTransaction

### ISSUE THREAD

**Issue by danielnordh** [simolus3/web3dart#122]
We are successfully creating new wallets, receiving both ETH and USDC but are not able to send either.
Getting the following error:

`RPCError: got code -32000 with msg "invalid sender"`

I'm guessing there's something wrong with the credentials but the code we use is very similar to the example code:

**ETH send**

```
final wallet = Web3Dart.Wallet.fromJson(user.ethereumWallet, kWalletPassword);
final credentials = wallet.privateKey;

await ethClient.sendTransaction(
        credentials,
        Web3Dart.Transaction(
          to: ethAddress,
          value:
              Web3Dart.EtherAmount.fromUnitAndValue(Web3Dart.EtherUnit.ether, 1),
        ));
```

**USDC transfer**

```
final wallet = Web3Dart.Wallet.fromJson(user.ethereumWallet, kWalletPassword);
final credentials = wallet.privateKey;
final contract = await ref.read(usdcContractProvider.future);

await ethClient.sendTransaction(
        credentials,
        Web3Dart.Transaction.callContract(
          contract: contract,
          function: contract.function('transfer'),
          parameters: [ethAddress, amount],
        ));
```

I have confirmed that both the Wallet and Credentials objects are instantiated properly.
Any ideas to what the problem could be here?

**Comment by simolus3** [comment]
Does it help if you add `fectChainIdFromNetworkId: true` to `sendTransaction` or specify the correct `chainId` manually?

**Comment by danielnordh** [comment]
Thank you for a very quick response.
Yes, setting `fectChainIdFromNetworkId: true` did solve that problem!

I was testing on Ropsten which might have been the issue, if the default is mainnet if this is not set.

The transactions now go through, but I get another rpc error:
 `msg "already known"`

Since the transactions work I'm not sure if I need to worry about this.
