### ISSUE TITLE
Decode Logs of Receipt

### ISSUE THREAD

**Issue by KRENERGY** [simolus3/web3dart#123]
Hello,

I have tried to figure out how to decode the logs of a transaction receipt with web3dart, but no successfully.
From the web3, my reference is. : web3.eth.abi.decodeLog(inputs, hexString, topics);

I have looked at open / closed issues ; a interesting output for the receipt mgt, but nothing on the 'decodeLog'.
Is it that it is not "facilitated" by the userfriendly web3dart and has to be done differently ?

Thanks in advance for your help.

**Comment by simolus3** [comment]
Web3Dart can now generate contract classes that decode transaction logs for you. Apart from that, you can use `contract.event('EventName').decodeResults()` to decode transaction logs into solidity events.
