### ISSUE TITLE
formatting.dart 

### ISSUE THREAD

**Issue by YoffieYF** [simolus3/web3dart#126]
The formatting.dart file need change
```dart
int hexToDartInt(String hex) {
  return int.parse(strip0x(hex));
}
```
to

```dart
int hexToDartInt(String hex) {
  return int.parse(strip0x(hex), radix: 16);
}
```

**Comment by simolus3** [comment]
This has long been fixed: 
https://github.com/simolus3/web3dart/blob/be09be2226529da9c5c7d57d46505d91e6c24956/lib/src/crypto/formatting.dart#L57-L60

Can you try using the `2.0.0-dev` versions of web3dart? I'll make them stable after migrating to null-safety (but so far we're still blocked on some dependencies)
