### ISSUE TITLE
Function encode list of Uint 256

### ISSUE THREAD

**Issue by Abhimanyu121** [simolus3/web3dart#128]
I am looking for a way to function encode Uint256 list using web3dart but could not find any good way. Is it possible with web3Dart?
This is the js equivalent of the snippet that I want to write in Dart.
```const depositData = mainWeb3.eth.abi.encodeParameters(
  ['uint256[]', 'uint256[]', 'bytes'],
  idList, amountList, data
)
await rootChainManagerContract.methods
  .depositFor(userAddress, rootToken, depositData)
  .send({ from: userAddress })
```

Thank you

**Comment by simolus3** [comment]
You can use 
- [DynamicLengthArray](https://pub.dev/documentation/web3dart/2.0.0-dev.9/contracts/DynamicLengthArray-class.html) for an array with a dynamic length
- [UintType](https://pub.dev/documentation/web3dart/2.0.0-dev.9/contracts/UintType-class.html) for unsigned ints
- [TupleType](https://pub.dev/documentation/web3dart/2.0.0-dev.9/contracts/TupleType-class.html) for multiple arguments

They all have an `encode` method that can be used to encode data. You can see an example on how to use that here:

https://github.com/simolus3/web3dart/blob/75ba97abe0c103182ff74a8983044dd4d2c7a700/lib/src/contracts/abi/abi.dart#L221
