### ISSUE TITLE
StateMutability error when parsing json abi that contains an event

### ISSUE THREAD

**Issue by DrasiusMajere** [simolus3/web3dart#13]
I'm using solidity version 0.5.0
when json abi string contains an event parameter the parse function still looks for statemutability key that in my case event types dont have that key in the interface, and the switch clause in the function in that case throws an error. 
That error is easy to solve but I'm doing tests so finally I ripped that part from abi. you can watch events to know when an state changes.

**Comment by maxholman** [comment]
@DrasiusMajere Just opened PR #17 which resolves this one

**Comment by DrasiusMajere** [comment]
It's working, but only moving the conditional to the beginning of the loop for is enough if you want to reuse var type.
thank you
