### ISSUE TITLE
getting NoSuchMethod Error on credentialsFromPrivateKey method

### ISSUE THREAD

**Issue by vibhavkarthik03** [simolus3/web3dart#133]
I'm trying to get the wallet address using the private key,

I'm able to get the private key, but i'm getting this error if i try to get wallet address.

E/flutter (19072): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method 'credentialsFromPrivateKey' was called on null.
E/flutter (19072): Receiver: null

**Comment by simolus3** [comment]
Are you sure you're calling that method on a non-null `Web3Client`? Can you post a stack trace?

**Comment by vibhavkarthik03** [comment]
My bad ! I didn't specify the RPC_URL before, 

After specifying the URL  everything works fine !
Thanks for the reply.
