### ISSUE TITLE
estimateGas function missing value field

### ISSUE THREAD

**Issue by Hanggi** [simolus3/web3dart#135]
I made a contract which checking msg.value is larger than the value of parameter.

but I found that the value field is missing in estimateGas function.

**Comment by simolus3** [comment]
The latest version (which is still a pre-review, I'll release that once all dependencies and this package have migrated to null-safety) contains the parameter in [estimateGas](https://pub.dev/documentation/web3dart/2.0.0-dev.9/web3dart/Web3Client/estimateGas.html).

**Comment by ttb-inc** [comment]
Can you tell when a null-safety supported version will be updated?

**Comment by simolus3** [comment]
We're missing some dependencies (`package:isolate` in particular). As soon as that one is done I'll start the migration, which shouldn't take long hopefully :)
