### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by vsilux** [simolus3/web3dart#136]
Hi, I just wondering to know are you planning to do migration to null safety?

**Comment by simolus3** [comment]
I am, but not all of our dependencies have migrated yet. As soon as that's complete I will migrate this package as well.

**Comment by hhstore** [comment]
# v2 Null Safety: 

- I submitted this PR, a temporary version.
- welcome to use this branch if necessary.

## PR: 

- PR here: https://github.com/simolus3/web3dart/pull/137

**Comment by treeder** [comment]
I made another PR with a more complete migration: https://github.com/simolus3/web3dart/pull/140

`json_rpc_2` is the last dependency that needs null safety.

**Comment by ttb-inc** [comment]
HI,
Can't I disable the [--no-sound-null-safety] option?
Testing is possible, but I can't make .apk .ㅡ,ㅡ;

**Comment by simolus3** [comment]
web3dart version 2.0.0 is out on pub and null safe.
