### ISSUE TITLE
Web3Client using Infura returning "Address has invalid case-characters and isthus not EIP-55 conformant"

### ISSUE THREAD

**Issue by ivankragoff** [simolus3/web3dart#138]
When initializing a web3client with a infura endpoint and doing a getBalance, I get invalid address. But when using ganache, I am able to get the correct balance on a sample account. 

```
// Returns 'Address has invalid case-characters and is thus not EIP-55 conformant'
var httpClient = new Client();
var ethClient = new Web3Client("https://mainnet.infura.io/v3/ID", httpClient);
ethClient.getBalance(EthereumAddress.fromHex(ethAddress));
```

```
// Returns correct sample balance
var httpClient = new Client();
var ethClient = new Web3Client("HTTP://192.168.0.70:8545", httpClient);
ethClient.getBalance(EthereumAddress.fromHex(ethAddressSample));
```

**Comment by simolus3** [comment]
If a hex address contains both uppercase and lowercase chars, we'll assume that it was formatted with EIP-55 and don't accept the address if there's a mismatch.
You could try using `ethAddress.toLowerCase()` to work. If you're receiving the `ethAddress` from infura and it's not private, can you post it with the exact casing and how you obtained the address?

**Comment by ivankragoff** [comment]
Thanks. To lowerCase worked.
