### ISSUE TITLE
Different result with publicKeyToAddress between PointyCastle 3.0.1 and 1.0.2 

### ISSUE THREAD

**Issue by redDwarf03** [simolus3/web3dart#139]
i have different result with publicKeyToAddress method since i upgrade to PointyCastle 3.0.1 (I was with 1.0.2)
With 1.0.2 the result was ok but now, not

The code of web3dart is actually
```
/// Constructs the Ethereum address associated with the given public key by
/// taking the lower 160 bits of the key's sha3 hash.
Uint8List publicKeyToAddress(Uint8List publicKey) {
  assert(publicKey.length == 64);

  final hashed = sha3digest.process(publicKey);
  return Uint8List.view(hashed.buffer, _shaBytes - 20);
}
```

But when I use sha3 plugin directly, I have the good address
```
 var k = SHA3(256, KECCAK_PADDING, 256);
 k.update(privateKeyBytesToPublic(HEX.decode(pk)));
 var hash = k.digest();
 int _shaBytes = 256 ~/ 8;
 hash = Uint8List.view(Uint8List.fromList(hash).buffer, _shaBytes - 20);
 ```

Any idea ?

**Comment by simolus3** [comment]
I think pointycastle's `sha3` algorithm (in 1.x) was actually the keccak variant, and they changed that to a consistent naming in pointycastle v2. web3dart should probably update that as well when supporting the latest pointycastle.

**Comment by redDwarf03** [comment]
yes. I discuss with PointyCastle dev
if web3dart migrate to PointyCastle 3.0.1 (and I think it's necessary), you should change 
```
sha3digest.process( ....
```

with 
```
KeccakDigest(256).process( ....
```

**Comment by simolus3** [comment]
Yeah, I started to work on that but I encountered many more such cases that are a lot less obvious. It will take some time for web3dart to support the latest dependencies.

**Comment by redDwarf03** [comment]
yes.
I found issue too with method decodeBigInt . now we can have negative bigint...
new code: https://github.com/bcgit/pc-dart/blob/be4142082f01cd3971bec4890342e039799c1f0e/lib/src/utils.dart#L19

```
/// Decode a BigInt from bytes in big-endian encoding.
/// Twos compliment.
BigInt decodeBigInt(List<int> bytes) {
  var negative = bytes.isNotEmpty && bytes[0] & 0x80 == 0x80;

  BigInt result;

  if (bytes.length == 1) {
    result = BigInt.from(bytes[0]);
  } else {
    result = BigInt.zero;
    for (var i = 0; i < bytes.length; i++) {
      var item = bytes[bytes.length - i - 1];
      result |= (BigInt.from(item) << (8 * i));
    }
  }
  return result != BigInt.zero
      ? negative ? result.toSigned(result.bitLength) : result
      : BigInt.zero;
}
```

old code:
```
BigInt decodeBigInt(List<int> bytes) {
  BigInt result = new BigInt.from(0);
  for (int i = 0; i < bytes.length; i++) {
    result += new BigInt.from(bytes[bytes.length - i - 1]) << (8 * i);
  }
  return result;
}
```

same pb with encodeBigInt

So i updated formatting.dart to play correctly with PointyCastle 3.0.1 with replacing new method by old method

**Comment by simolus3** [comment]
Thanks! I've found the issues with int encoding/decoding too and pushed my adaption to the `upgrade-pointycastle` branch in this repo. There are still some issues in secp256k1.dart that I didn't investigate yet.

**Comment by redDwarf03** [comment]
can I help you ? what is the issue in secp256k1.dart ?
in my project, I dev a signer method with PointyCastle 3.0.1 and asn1lib. I don't know if it could help you :

```
  String signString(String privateKey, String msgToSign) {
    final ECDSASigner signer = Signer('SHA-256/ECDSA');

    final _privateKey = ECPrivateKey(
      BigInt.parse(privateKey, radix: 16),
      ECDomainParameters('secp256k1'),
    );
    var privParams = PrivateKeyParameter(_privateKey);

    final rnd = new SecureRandom("AES/CTR/PRNG");
    final key = getSecureRandom(16);
    final iv = getSecureRandom(16);
    final keyParam = new KeyParameter(new Uint8List.fromList(key));

    final params = new ParametersWithIV(keyParam, new Uint8List.fromList(iv));
    rnd.seed(params);

    signer.reset();
    signer.init(true, new ParametersWithRandom(privParams, rnd));
    ECSignature sig = signer.generateSignature(utf8.encode(msgToSign));
    sig = sig.normalize(ECDomainParameters('secp256k1'));

    var topLevel = new asn1lib.ASN1Sequence();
    topLevel.add(asn1lib.ASN1Integer(sig.r));
    topLevel.add(asn1lib.ASN1Integer(sig.s));

    var sig64 = base64.encode(topLevel.encodedBytes);

    //print("return sig64 : " + sig64);
    return sig64;
  }
```

**Comment by simolus3** [comment]
The current version on the master branch supports the latest PointyCastle version.
