### ISSUE TITLE
Breaking changes on solidity 0.5.0 regarding Strings, bytes, padding and conversions

### ISSUE THREAD

**Issue by DrasiusMajere** [simolus3/web3dart#14]
When I call a function on a contract(compiled solc0.5.0) that is returning a String value an error arises complaining about value not in range but the problem is in decode functions on dynamiclengthbytes and staticlengthbytes, I presume is due to the breaking changes in the new solidity version regarding left-aligned hex representation of String and padding issues, or maybe this 
"Conversions between bytesX and uintY of different size are now disallowed due to bytesX padding on the right and uintY padding on the left which may cause unexpected conversion results. The size must now be adjusted within the type before the conversion"
I don't understand too much about it because I'm starting learning solidity and ethereum.

**Comment by simolus3** [comment]
Hey, thanks for pointing this out. I think that quote only refers to the Solidity language itself and not to the encoding per se, but I'll try to grab some test encodings from other Ethereum clients to see if they encode strings differently. That should help to find the exact problem.

**Comment by simolus3** [comment]
I just checked whether the test cases of web3j, notably https://github.com/web3j/web3j/blob/master/abi/src/test/java/org/web3j/abi/TypeEncoderTest.java and https://github.com/web3j/web3j/blob/master/abi/src/test/java/org/web3j/abi/TypeEncoderTest.java for strings and static / dynamic length bytes also work for this library and they produce the expected output...
Can you help me with this by giving an example of a contract definition that returns a string that can't be decoded by this library? That would really be helpful!

**Comment by DrasiusMajere** [comment]
Ropsten
Address: `0xD73845bba002a3f2a5c2DF835fD67d282afbf4E8`
ABI: `[ { "constant": true, "inputs": [ { "name": "fileHash", "type": "string" } ], "name": "getOwner", "outputs": [ { "name": "", "type": "string", "value": "" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0x4aaf4a12" }, { "constant": true, "inputs": [ { "name": "fileHash", "type": "string" } ], "name": "get", "outputs": [ { "name": "", "type": "uint256", "value": "1542556069" }, { "name": "", "type": "string", "value": "pepito" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0x693ec85e" }, { "constant": true, "inputs": [ { "name": "fileHash", "type": "string" } ], "name": "getTime", "outputs": [ { "name": "", "type": "uint256", "value": "0" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0xb359cedd" }, { "constant": false, "inputs": [ { "name": "owner", "type": "string" }, { "name": "fileHash", "type": "string" } ], "name": "set", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function", "signature": "0xe942b516" }, { "anonymous": false, "inputs": [ { "indexed": false, "name": "status", "type": "bool" }, { "indexed": false, "name": "timestamp", "type": "uint256" }, { "indexed": false, "name": "owner", "type": "string" }, { "indexed": false, "name": "fileHash", "type": "string" } ], "name": "logFileAddedStatus", "type": "event", "signature": "0x0d3bbc3c02da6ed436712ca1a0f626f1269df703a105f034e4637c7b10fb7ba5" } ]`

P.D: soljs, remix, etherscan are not able to create the bytecode yet. I've used solc to compile it.

**Comment by DrasiusMajere** [comment]
Silly question why prepareForPaymentCall, prepareForCall functions need DeployedContract instance if transaction object already has credentials and send and call methods has to pass them web3client. Is it not sufficient with EthereumAddress?
I have too many things to learn, it's huge this cryptoworld

**Comment by simolus3** [comment]
Thanks for the contract. Can you give me some sample method invocation that fails in web3dart? Any `fileHash` I can put into `getOwner` should return a string that breaks in web3dart, right?
> Silly question why prepareForPaymentCall, prepareForCall functions need DeployedContract instance if transaction object already has credentials and send and call methods has to pass them web3client. Is it not sufficient with EthereumAddress?

Not a silly question at all! You're right, the `EthereumAddress` would suffice. My idea was that users should only have to specify that whole thing once. Also, I planned that this library might do some code-generation based on contract ABIs to convert them into dart classes. Then, we could just have something like `MyContract(credentials, client, address).getOwner(fileHash)` and call all other functions on `MyContract` without having to specify everything for each function call.
However, I didn't have the time to implement this yet so right now everything is pretty low-level and this is indeed irrelevant information passed to the contract object.
> I have too many things to learn, it's huge this cryptoworld

Yeah, I feel like that as well sometimes, I also don't have any experience with cryptocurrencies except for this library. Put poking around with some code helps. In fact, I mainly started this library to learn about some low-level basics about Ethereum transactions :smiley:

**Comment by simolus3** [comment]
This should now be fixed in version `0.4.5` on pub, sorry for taking this long. I didn't catch it earlier because all the types are decoding properly, it's just the function decoder that messes things up. Many thanks to @xiaoch05 for pointing out the error. Let me know if it still doesn't work.
