### ISSUE TITLE
Version incompatibilities with latest packages uuid, http, pointycastle

### ISSUE THREAD

**Issue by degloff** [simolus3/web3dart#145]
For various dependency reasons I had to upgrade several packages which required me to do overrides.
I tried with webdev 1.2.3 and also recent dev versions.

 I need to add the following overrides in pubspec.yaml because of web3dart version issues:

  uuid: any
  pointycastle: any
  http: any

There is now an issue with uuid version. Can you update your dependency and create a version that can handle the latest packages of uuid, pointycastle and http?

Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/web3dart-1.2.3/lib/json_rpc.dart:34:7: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
      url,
      ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/web3dart-1.2.3/lib/src/utils/uuid.dart:8:44: Error: The method 'unparse' isn't defined for the class 'Uuid'.
 - 'Uuid' is from 'package:uuid/uuid.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/uuid-3.0.4/lib/uuid.dart').
Try correcting the name to the name of an existing method, or defining a method named 'unparse'.
String formatUuid(List<int> uuid) => _uuid.unparse(uuid);
                                           ^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/web3dart-1.2.3/lib/src/utils/uuid.dart:19:9: Error: The method 'parse' isn't defined for the class 'Uuid'.
 - 'Uuid' is from 'package:uuid/uuid.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/uuid-3.0.4/lib/uuid.dart').
Try correcting the name to the name of an existing method, or defining a method named 'parse'.
  _uuid.parse(uuid, buffer: buffer);
        ^^^^^

FAILURE: Build failed with an exception.

**Comment by simolus3** [comment]
Which web3dart version are you using exactly? I've published some pre-releases of 2.0.0-dev to pub that should support the latest dependencies.

**Comment by simolus3** [comment]
I've just published version 2.0 which supports all the latest dependencies.
