### ISSUE TITLE
How can I add other commands?

### ISSUE THREAD

**Issue by ttb-inc** [simolus3/web3dart#147]
Hi,
Thank you for the update.

How can I add other commands?
ex, 'eth_getBlockByNumber', ...
or
Can We3Client be extended and used?
(_makeRPCCall)

Thank you.

**Comment by simolus3** [comment]
If you think it's a new command that would be generally useful, I think a pull request is the best option :smile: 

We could expose `_makeRPCCall`, but that only really makes sense if the node you're talking to contains custom methods.

**Comment by ttb-inc** [comment]
I got it.
I am going to work and will a pull request.
Thank you.
