### ISSUE TITLE
invalid sender when sending a transaction using prepareforpaymentcall

### ISSUE THREAD

**Issue by DrasiusMajere** [simolus3/web3dart#15]
I'm using a solidity contract version 0.5.0 and infura for sending transactions. The function is not payable
for this reason I'm using EtherAmount.zero() parameter

> E/flutter (16270): RPCError: got code -32000 with msg "invalid sender".
 E/flutter (16270): #0      JsonRPC.call (package:web3dart/src/io/jsonrpc.dart:47:4)
E/flutter (16270): <asynchronous suspension>
E/flutter (16270): #1      Web3Client._makeRPCCall (package:web3dart/src/web3client.dart:29:30)
E/flutter (16270): <asynchronous suspension>
E/flutter (16270): #2      Web3Client.sendRawTransaction (package:web3dart/src/web3client.dart:177:10)
E/flutter (16270): #3      FinalizedTransaction.send.<anonymous closure> (package:web3dart/src/transaction.dart:112:18)

**Comment by maxholman** [comment]
@DrasiusMajere Are you using ropsten?

I just submitted PR #16 that will allow you to specify a `chainId` for transactions. I was getting this same error using infura/ropsten.

**Comment by DrasiusMajere** [comment]
Yes, I'm testing and obviously using ropsten....
Thank you for the support because I'm a newbie in ethereum
But I hope this package will be updated to the solidity 0.5.0

**Comment by maxholman** [comment]
The PR will allow you to specify a `chainId` like this, that should solve the invalid sender error.

```dart
transaction.prepareForSimpleTransaction(
  new EthereumAddress("0x[...]"), // your target address 
  EtherAmount.fromUnitAndValue(EtherUnit.finney, 300)
).send(ethClient, chainId: 3);
```

**Comment by DrasiusMajere** [comment]
It's working.
Now to send a transaction that calls a function that alters state variables is possible.

**Comment by ishwarchandratiwari** [comment]
> The PR will allow you to specify a `chainId` like this, that should solve the invalid sender error.
> 
> ```dart
> transaction.prepareForSimpleTransaction(
>   new EthereumAddress("0x[...]"), // your target address 
>   EtherAmount.fromUnitAndValue(EtherUnit.finney, 300)
> ).send(ethClient, chainId: 3);
> ```

i had a same issue invalid sender when sending a transaction,
your snippet worked, but how can i get Transaction id ?

**Comment by DrasiusMajere** [comment]
Actually send method return that, if you want an hexadecimal id more readable. I found a function that uses web3dart called bytesToHex.
`var tranId = bytestoHex(await transaction.prepareForSimpleTransaction(
  new EthereumAddress("0x[...]"), // your target address 
  EtherAmount.fromUnitAndValue(EtherUnit.finney, 300)
).send(ethClient, chainId: 3));`

Maybe it would be recommended divide the code above in smaller parts.

**Comment by ishwarchandratiwari** [comment]
Thanks

**Comment by ishwarchandratiwari** [comment]
> Actually send method return the transaction Id as a list of bytes, if you want an hexadecimal id more readable. I found a function that uses web3dart called bytesToHex.
> `var tranId = bytestoHex(await transaction.prepareForSimpleTransaction( new EthereumAddress("0x[...]"), // your target address EtherAmount.fromUnitAndValue(EtherUnit.finney, 300) ).send(ethClient, chainId: 3));`
> 
> Maybe it would be recommended divide the code above in smaller parts.

i am getting error
The method 'bytestoHex' isn't defined for the class 'main'.

**Comment by DrasiusMajere** [comment]
`import 'package:web3dart/conversions.dart';`

What IDE are you using? because you can leave the IDE looks for the appropriate library that contains that function and add the import statements automatically.
