### ISSUE TITLE
error when abi.json have other types than function and event.

### ISSUE THREAD

**Issue by benzsuankularb** [simolus3/web3dart#154]
For example, Erc20 has the type `fallback` in the ABI file.
```
{
        "payable": true,
        "stateMutability": "payable",
        "type": "fallback"
},
```

Or Pancakeswap router has the type `receive` in the ABI file.
```
{
       "stateMutability":"payable",
       "type":"receive"
}
```

This cause an error when generating file using build runner.
`Null check operator used on a null value`

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this problem and the other one you reported in version 2.1.2 of web3dart.
