### ISSUE TITLE
Sign Json Transaction

### ISSUE THREAD

**Issue by nomanmurtaza786** [simolus3/web3dart#155]
Hi how can I sign a JSON transaction like this 
{
  "price": "0.002663907000981641",
  "guaranteedPrice": "0.002637267930971825",
  "to": "0xdef1c0ded9bec7f1a1670819833240f027b25eff",
  "data": "0xd9627aa40000000000000000000...",
  "value": "0",
  "gas": "111000",
  "estimatedGas": "111000",
  "gasPrice": "44000000000",
  "minimumProtocolFee": "0",
  "buyTokenAddress": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
  "sellTokenAddress": "0x6b175474e89094c44da98b954eedeac495271d0f",
  "buyAmount": "2663907000981641103",
  "sellAmount": "1000000000000000000000",
  "allowanceTarget": "0xf740b67da229f2f10bcbd38a7979992fcc71b8eb"
}

**Comment by simolus3** [comment]
Can you post more details on what kind of transaction that is?

Typically, signing an Ethereum transaction involves a binary encoding of the transaction's fields so it's not obvious how additional data would be integrated into that. You can use the `signToSignature` method on `Credentials` to obtain a (r, s, v) triple for any byte string if that's what you're looking for.

If this is a transaction to smart contract, there are other ways to send it.

**Comment by nomanmurtaza786** [comment]
Hi Simolus
Thanks for the reply.
Please check this.

https://0x.org/docs/guides/swap-tokens-with-0x-api

**Comment by nomanmurtaza786** [comment]
actually want to implement this thing https://0x.org/docs/guides/swap-tokens-with-0x-api

**Comment by simolus3** [comment]
Reading the documentation, it became clear to me that the majority of fields in that JSON are just ignored :D A subset of fields in the JSON are used to construct an Ethereum transaction, the important bits are stored in the receiver and the `data` passed to the contract invocation.
So, if `json` was a `Map<String, dynamic>` of your target transaction, you can send it like this:

```dart
import 'package:web3dart/crypto.dart';
import 'package:web3dart/web3dart.dart';

// ...
final transaction = Transaction(
  to: EthereumAddress.fromHex(json['to'] as String),
  maxGas: hexToDartInt(json['gas']! as String),
  gasPrice: EtherAmount.inWei(hexToInt(json['gasPrice']! as String)),
  value: EtherAmount.inWei(hexToInt(json['value']! as String)),
  data: hexToBytes(json['data']! as String),
);

client.sendTransaction(yourCredentials, transaction);
```

**Comment by nomanmurtaza786** [comment]
Hi Simolus this thing closed with fail transaction 

https://bscscan.com/tx/0x47494421e78294783f775d9636def5a1903c1aaa358cb9b5def403e3d5cac68b
