### ISSUE TITLE
Json Transaction

### ISSUE THREAD

**Issue by nomanmurtaza786** [simolus3/web3dart#157]
I am trying to sign this transaction but with few parameters, it gets failed. As we discussed. Is there any way to sign additional parameters? 
When I tried to sign with other methods but it asked for Unit8list. 

https://bscscan.com/tx/0x47494421e78294783f775d9636def5a1903c1aaa358cb9b5def403e3d5cac68b

Can you please try this code. Really he appreciates your help. 

import 'dart:convert';
import 'dart:typed_data';

import 'package:http/http.dart' as http;
//import 'package:web3dart/contracts/erc20.dart';
import 'package:web3dart/crypto.dart';
import 'package:web3dart/web3dart.dart';
import 'package:web_socket_channel/io.dart';
import 'package:web_socket_channel/web_socket_channel.dart';
//import 'package:ethereum/ethereum.dart';

const String privateKey =
    'key';
//const String rpcUrl = 'https://bsc-dataseed1.binance.org:443'; this is mainnet
//const String wssUrl = 'wss://bsc-dataseed1.binance.org:443';

const String rpcUrl = 'https://data-seed-prebsc-1-s1.binance.org:8545'; //testnet
const String wssUrl = 'wss://data-seed-prebsc-1-s1.binance.org:8545';
const String oxurl =
    'https://bsc.api.0x.org/swap/v1/quote?buyToken=0xD7730681B1DC8f6F969166B29D8A5EA8568616a3&sellToken=WBNB&sellAmount=1000000000000000000&slippagePercentage=0.05';

var guaranteedPrice;
var price;
var to;
var data;
var value;
var gas;
var gasPrice;
var sellAmount;
var buyAmount;
var estimatedGas;
var allowanceTarget;
var minimumProtocolFee;
var buyTokenAddress;
var sellTokenAddress;

Future<void> main() async {
  // start a client we can use to send transactions

  var response = await http.get(Uri.parse(oxurl));
  var json = await jsonDecode(response.body);

  //print(json);

  final client = Web3Client(rpcUrl, http.Client(), socketConnector: () {
    return IOWebSocketChannel.connect(wssUrl).cast<String>();
  });

  final credentials = await client.credentialsFromPrivateKey(privateKey);
  final address = await credentials.extractAddress();

  print(address.hexEip55);
  print(await client.getBalance(address));

  var signedTx = await client.signTransaction(
    credentials,
    Transaction(
      to: EthereumAddress.fromHex(json['to']),
      //gasPrice: EtherAmount.inWei(BigInt.one),
      maxGas: hexToDartInt(json['gas']),
      data: hexToBytes(json['data']),
      value: EtherAmount.inWei(
        hexToInt(json['value']),
      ),
    ),
    //fetchChainIdFromNetworkId: true,
    chainId: 56,
  );

  var txlist = [
    {price, json['price']},
    {guaranteedPrice, json['guaranteedPrice']},
    {to, json['to']},
    {data, json['data']},
    {value, json['value']},
    {gas, json['gas']},
    {estimatedGas, json['estimatedGas']},
    {gasPrice, json['gasPrice ']},
    {minimumProtocolFee, json[' minimumProtocolFee']},
    {buyTokenAddress, json[' buyTokenAddress']},
    {sellTokenAddress, json['sellTokenAddress']},
    {buyAmount, json['buyAmount']},
    {sellAmount, json['sellAmount']},
    {allowanceTarget, json[' allowanceTarget ']},
  ];
 

  //final signedTx2 = await client.signTransaction(credentials, json);
  //var txSent = await client.sendRawTransaction(signedTx);
  //print(txSent);
  await client.dispose();
}

**Comment by kaumudpa** [comment]
Were you able to connect it to Binance Smart Chain? BEP20?
