### ISSUE TITLE
No checksum address method found

### ISSUE THREAD

**Issue by Flaming19** [simolus3/web3dart#159]
checkAddressChecksum

web3.utils.checkAddressChecksum(address)

this method is not found in this library, Is there any way to get this in flutter?

**Comment by simolus3** [comment]
I don't know what exactly `checkAddressChecksum` does (the docs are kind of lacking), but you can do this:

```dart
try {
  EthereumAddress.fromHex(yourString, enforceEip55: true)
  // valid!
} on ArgumentError {
  // Not valid
}

```

**Comment by Flaming19** [comment]
https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#checkaddresschecksum

 {EthereumAddress.fromHex(yourString, enforceEip55: true) is something else.}

This method gives us correct Address of any token from chain.

**Comment by simolus3** [comment]
But that upper/lowercase thing is just about eip55, right? That would be caught by `EthereumAddress.fromHex` then.

If you want to convert to a checksum address you could use `EthereumAddress.hexEip55` then.

**Comment by Flaming19** [comment]
I used EthereumAddress.fromHex with enforceEip55: true, but it is not working.

Correct token address can be get from chain only by toChecksumAddress method. If you have any example, Please share with me.

**Comment by simolus3** [comment]
What is your input data? A string where you want to check that is has the right upper/lowercase chars according to the hashsum?

**Comment by Flaming19** [comment]
Input Data is [0xfeea0bdd3d07eb6fe305938878c0cadbfa169042] and right upper/lowercase is [0xFeea0bDd3D07eb6FE305938878C0caDBFa169042]

**Comment by simolus3** [comment]
What's wrong with this then?

```dart
import 'package:web3dart/web3dart.dart';

void main() {
  final address =
      EthereumAddress.fromHex('0xfeea0bdd3d07eb6fe305938878c0cadbfa169042');
  print(address.hexEip55); // 0xFeea0bDd3D07eb6FE305938878C0caDBFa169042
}

```

**Comment by Flaming19** [comment]
Great,
Thankyou very much for your help.
