### ISSUE TITLE
sendTransaction freeze Flutter UI

### ISSUE THREAD

**Issue by francescofact** [simolus3/web3dart#160]
Hi, i have made these two function that i call from an ElevatedButton in futter.
The main problem is that if i call _sendVote() the main thread freeze until the sendTransaction returns.

```
void _sendVote() async {
    List<dynamic> args = [true, BigInt.from(1000000000000000000)];
    try {
      await query("cast_envelope", args);
      debugPrint("SUCCESS");
    } catch(error) {
      debugPrint(error.toString());
    }
```

```
Future<void> query(String fun, List<dynamic> args, {int wei=0}) async {
    await ethClient.sendTransaction(creds, Transaction.callContract(
      contract: contract,
      function: contract.function(fun),
      parameters: args,
      value: EtherAmount.inWei(BigInt.from(wei)),
      maxGas: 999999,
    ));
 }
```

Why doesn't it execute the functions in background?

**Comment by simolus3** [comment]
Signing the transaction is the only expensive (and synchronous) thing that comes to mind - all the other operations are asynchronous. A previous version of `web3dart` had support to compute signatures in a background isolate, but that was removed because the `isolate` package hadn't been migrated to null safety at the time. I think I can add that feature back now.

**Comment by francescofact** [comment]
Ok, thank you.
Let me know when you restore the Isolate functionality.

**Comment by francescofact** [comment]
What is the latest version that support the isolate package if i turn null safety off?
Will i miss a lot of fixes?

**Comment by simolus3** [comment]
I think it should be `2.0.0-dev.9`, I don't think that there were any severe bugfixes since then.

**Comment by k9nine-dev** [comment]
I was just using the `compute()` method and everything was working fine. keep in mind that the function you are working with has to be a top level function.

```
Future<String> _signTransaction(SignTransactionParams params) async { 
.......
}
```

`var signed = await compute(_signTransaction, params);`

I'm sure the same could be done with `sendTransaction()` no?

**Comment by simolus3** [comment]
It would require you to construct the client on a background isolate as well, but in general it should work.

Closing this as `package:isolate` has been discontinued. If you want to run expensive operations, my suggestion is to use `compute` to sign the transaction as well.
