### ISSUE TITLE
How to use Flutter Web3Dart to implement web browser loading dApp?

### ISSUE THREAD

**Issue by EvnLi** [simolus3/web3dart#163]

**Comment by EvnLi** [comment]
It is not a web page. I want to realize the DAPP browser through WebView in the APP application. I have not found relevant information for a long time, is there any way to achieve it? Thank you very much!

**Comment by EvnLi** [comment]
Similar common dApp browsers include Mist, Metamask, Coinbase Wallet, Trust Wallet, ImToken, Status, Cipher, etc

**Comment by simolus3** [comment]
Which webview package are you using? Can you inject arbitrary JavaScript into the page shown in your webview (or force shown pages to add a JS library you control)?

**Comment by EvnLi** [comment]
flutter_inappwebview,Browsers are built with Similar common dApp including Mist, Metamask. Browsers are built with flutter_inappWebView. Browsers are built with Similar common dApp including Mist, Metamask. Coinbase Wallet, Trust Wallet, IMToken, Status, Cipher, etc. By entering the address of the DAPP project, you can authorize your own Wallet account information. In fact, it is just how to realize the DAPP browser

**Comment by simolus3** [comment]
You can use [`addJavaScriptHandler`](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/InAppWebViewController/addJavaScriptHandler.html) to add a custom callback that can be called in the website you're showing. This callback could be used to execute an Ethereum rpc call. Then, you can use [`injectJavascriptFileFromAsset`](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/InAppWebViewController/injectJavascriptFileFromAsset.html) to inject a JavaScript file implementing `window.ethereum` over that custom injected callback.

**Comment by EvnLi** [comment]
Thank you very much!

**Comment by windswrold** [comment]
@EvnLi  Can you please consult how to use Flutter Web3Dart to implement web browser loading dApp?

**Comment by athlona64** [comment]
@EvnLi Can you please consult how to use Flutter Web3Dart to implement web browser loading dApp?
