### ISSUE TITLE
Why is strength not exposed in generateMnemonic function?

### ISSUE THREAD

**Issue by wal33d006** [simolus3/web3dart#164]
I can see `bip39.generateMnemonic` from `package:bip39/bip39.dart` gives the privilege of varying the strength. Why does `generateMnemonic` not do that? I want to generate a mnemonic with 256 strength.

**Comment by simolus3** [comment]
There's no `generateMnemonic` function in web3dart? Are you sure you have the right package? Maybe I'm missing something?

**Comment by wal33d006** [comment]
Sorry, my bad
