### ISSUE TITLE
Is estimateGas function malfunctioning?

### ISSUE THREAD

**Issue by mdat31** [simolus3/web3dart#175]
Here is my code
```
  final res = await web3Client.estimateGas(
      sender: _sender,
      to: _to,
      value: EtherAmount.fromUnitAndValue(EtherUnit.finney, 100),
      gasPrice: EtherAmount.fromUnitAndValue(EtherUnit.gwei, 20),
    );
```
I set the gasPrice to 20 gwei, should the result is 42000? I'm receiving 21000.

And for token estimate gas
```
    final trans = Transaction.callContract(
      contract: xrp.self,
      function: xrp.self.function('transfer'),
      gasPrice: EtherAmount.fromUnitAndValue(EtherUnit.gwei, 20),
      parameters: [
        to,
        0.1.toWei,
      ],
    );
```

Estimate for token send from _sender to trans.to
```
testClient.estimateGas(
      sender: _sender,
      to: trans.to,
      value: trans.value,
      data: trans.data,
    )
```

Compare to result on metamask, it's not equal

**Comment by JavonneM** [comment]
> I set the gasPrice to 20 gwei, should the result is 42000? I'm receiving 21000.
From my understanding 21000 is the minimum (or Standard) gas price.

**Comment by mdat31** [comment]
> > I set the gasPrice to 20 gwei, should the result is 42000? I'm receiving 21000.
> 
> From my understanding 21000 wei is the minimum (or Standard) gas price.

yes, it's true, it's minimum with `gasPrice = 10` and `gasLimit = 2100` => `gasFee = gasPrice * gasLimit`
The problem is when i set `gasPrice` to `20` the result of `gasFee` should be 42000

**Comment by kaumudpa** [comment]
yes looks like estimateGas is not working properly.

**Comment by opiator** [comment]
@mdat31 the estimateGas function measures the amount of gas units a transaction is likely to consume - 21000 is the minimum amount of gas units a tx will consume on ETH. 

You need to manually calculate the total fee by multiplying the result with the current gasPrice eg totalfee = estimategas(tx) * gasPrice

**Comment by kaumudpa** [comment]
We understand. But how do we estimate the gas price of a contract from abi?

How do we execute something like this from JS?

```
let abi = [ { … } ]

const contract = web3.eth.contract(abi).at(token_address);

let result = contract.transfer.estimateGas(to_address, token_val, {from: my_account});

console.log(result)

**Comment by opiator** [comment]
@kaumudpa you can use the generated contract classes that the web3dart generates for you - build up a transaction object and then send it in the "data" field of the estimateGas function.:

I have provided a snippet below:

```
    final function = yourGeneratedContractClassName.self.function('theSmartContractFunctionName');
    final params = [yourcustomParameterForFunction];
    
    final transaction = await Transaction.callContract(
      contract: contract,
      function: function,
      parameters: params,
      maxGas: (gasLimit != null) ? gasLimit.toInt() : null,
      gasPrice: gasPrice,
      value: (value != null) ? EtherAmount.inWei(value) : null,
    );

    await gasPriceLimit = await client.estimateGas(
          sender: sender,
          to: contract.self.address,
          data: transaction.data,
          gasPrice: _gasPrice,
          value: (value != null) ? EtherAmount.inWei(value) : null,
     );
```

**Comment by mdat31** [comment]
So i need to calculate it myself. Thanks!

**Comment by mdat31** [comment]
Hi, i'm having some issue about estimate a ERC20 token gasLimit
