### ISSUE TITLE
version > 2.0.0 and webdev incompatibility ? 

### ISSUE THREAD

**Issue by garyng2000** [simolus3/web3dart#181]
I tried to include 2.1.4 into my simple web application and there are conflicts with the build_config etc.

If I used 2.0.0, it has some problem handling my ERC721 abi in the ContractAbi constructor.

This seems to be due to the code generation introduced which requires the build_config package etc.

How can I use 2.1.4 in this context ?

**Comment by simolus3** [comment]
You should complain about `webdev` not supporting the latest dependencies, that always annoys me as well. You can also remove `webdev` from your pubspec and use `dart pub global webdev ...` instead.

What error message are you getting from pub exactly? For me it's webdev not supporting the latest `io` package which sounds like a problem with `webdev` to me.

**Comment by garyng2000** [comment]
the conflict comes from the build_config package use between webdev and web3dart. I am using the global webdev(2.59, 2.6 and 2.7 tried) all ends up the same problem. 

anyway, I have clone this project and change the build_config package dep(so use local copy rather than from the published one) and it works now.

just curious though, how can anyone using 2.1.4 for flutter which targets web ?
