### ISSUE TITLE
How to get token ERC 20 transfered value?

### ISSUE THREAD

**Issue by mdat31** [simolus3/web3dart#183]
I used generated token code to transfer `1 BUSD` and receive a transaction hash.
When i `getTransactionByHash` it does not get the `BUSD` value transfered.
How can i get it?

![image](https://user-images.githubusercontent.com/57827919/126424992-d83950d5-b691-43c0-96cd-2795ffd8393a.png)

**Comment by simolus3** [comment]
I think you can listen for the transfer event generated in that transaction to get the amount?

**Comment by mdat31** [comment]
The `TransactionInformation` does not include the token transfered, right?

**Comment by simolus3** [comment]
The `TransactionInformation` contains the input data, which you could use to re-construct the exact method call and parameters. But I think loading events from a transaction and decoding them leads better results, you can see an example for that here:

https://github.com/simolus3/web3dart/blob/af4c3fb4a0c258f4146f051e4c27d1674046003b/example/contracts.dart#L68-L70

**Comment by mdat31** [comment]
Thanks!
