### ISSUE TITLE
Validate ethereum private key?

### ISSUE THREAD

**Issue by mdat31** [simolus3/web3dart#185]
how can i validate a string hex is a private key before `web3.credentialsFromPrivateKey()`. Because i use an address on it, no error throw

**Comment by simolus3** [comment]
Pretty much all 256-bit keys are valid private keys in secp256k1. The only restriction is that interpreting them as unsigned int must yield a value from `1` to `n-1`, inclusive.

```dart
bool isValidPrivateKey(String hex) {
  final sk = bytesToUnsignedInt(hexToBytes(hex));
  final params = ECCurve_secp256k1();
  return sk >= BigInt.one && sk < params.n;
}
```

**Comment by mdat31** [comment]
Hi, i try with address and it's still valid

**Comment by simolus3** [comment]
I wouldn't be surprised if most Ethereum addresses are valid private keys to another address, that's just how secp256k1 works.
