### ISSUE TITLE
Feature Request: option to set the 'n' parameter of scrypt algorithm.

### ISSUE THREAD

**Issue by CosimoSguanci** [simolus3/web3dart#19]
As the default n parameter for the scrypt algorithm in wallet.dart, Wallet createNew(...), is 8192, I think you should add a method to customize this value. In fact, 2014 is a more suitable value, balanced between security and time to produce the keystore.

**Comment by simolus3** [comment]
Thanks for the suggestion, I'll add it to the library. 
Unrelated to that, do you have any evidence for 2048 being a more suitable value? The first article I've found regarding this is [this one](https://blog.filippo.io/the-scrypt-parameters/https://blog.filippo.io/the-scrypt-parameters/), which suggests to use higher values. I actually didn't find any source recommending smaller values so I'm wondering why you would want 2048?

**Comment by simolus3** [comment]
`Walltet.createNew` now has an optional parameter called `scryptN` with version `0.4.3` (just out on pub).
I'm still interested where you got 2014 from though :smile:

**Comment by CosimoSguanci** [comment]
I made a typing error, I meant that 1024 is a more suitable value. I can't open the page you linked. Obviously a greater 'n' parameters means more security. But 1024 is still a secure value, and it's more balanced between time of execution to create a new wallet and security. (https://ethereum.stackexchange.com/questions/9004/does-a-greater-number-of-hashing-rounds-in-aes-128-ctr-scrypt-key-generation-mea/9016)
