### ISSUE TITLE
API Documentation on how to create the wallet files, HD wallets

### ISSUE THREAD

**Issue by eddywm** [simolus3/web3dart#2]
It would be great if you could add more documentation on how to create a fresh new wallet.

All the interesting stuffs like HD Wallets, Mnemonic recovery, ...
I'd really like to see if I can use this lib in my flutter application.

**Comment by simolus3** [comment]
Hi. This library does not support 'fancy' wallet stuff yet, only some simple methods dealing with the private key directly. But I'll look into adding support for more sophisticated wallets if you need it.

**Comment by eddywm** [comment]
Hi @simolus3 I may even be willing to contribute to this lib.

I have been developping wallets on the Android platform prior to discovering Flutter months ago, now I can't think a mobile development world without Flutter and all the benefits it brings in terms of dev time and productivity.

**Comment by eddywm** [comment]
Are you planning to add support for  those ```fancy wallet stuff ``` 
If so I can help since I have a decent understanding of Mnemonic derivations and the HD wallets for the bitcoin blockchain, it might an opportunity for me to understand the Ethereum way of doing these stuffs.

**Comment by simolus3** [comment]
I am. However, I've already started implementing wallet loading and decryption following [this standard](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition), so I think the best way here would be to wait until I've published the basic code dealing with wallets (should only take 1-2 from now, I hope). After that, you can add support for Mnemonics or more sophisticated use-cases of Wallets into this library if you want to.

**Comment by eddywm** [comment]
Great !

**Comment by simolus3** [comment]
I've published an update with wallet support to this repository, but its not out on pub yet so that I can get some feedback as it breaks backwards compatibility. 
Check the readme for details on how wallet support is designed in this library. Let me know if that's helpful for you. It does not contain anything dealing with mnemonics, just the minimum support for the Web3 Secret Storage Definition. 
If you want to try this version of the library, change the dependency to this:
```yaml
dependencies:
  web3dart:
    git: https://github.com/simolus3/web3dart.git
```

**Comment by eddywm** [comment]
Excellent I have started to try it, I have just realized the type mismatch error that was surfacing is now fixed and a couple of API changes you have made.

On the other news, I started the mnemonic generation work following the web3j and others, and I have been able to get somewhere. 
I was just waiting for you to publish these changes to propose a merge request in the development branch so that you can see what I have been doing and whether you can improve the code ( I'm still learning the idiomatic Dart though. ).
