### ISSUE TITLE
bugfix:contract function's response parsed error.

### ISSUE THREAD

**Issue by xiaoch05** [simolus3/web3dart#21]
the next line at abi.dart:327 in function decodeReturnValues should be changed as follows:
           var decodedRaw = param.type.decodeRest(data);
===> var decodedRaw = param.type.decodeRest(modifiedData);

otherwise, the response cannot be parsed correctly.

**Comment by simolus3** [comment]
Stupid me :man_facepalming: Thanks for pointing this out, I fixed it in a0968df6745214601409e49a261711b778b3e027 which has also been released as `0.4.5` on pub.
