### ISSUE TITLE
bugfix: contract called response parsed failed for a dynamic length data.

### ISSUE THREAD

**Issue by xiaoch05** [simolus3/web3dart#22]
It's not very sure that the code should be modified as follows, but for the original code when I test an **empty String** type data response, it would be failed. And the modified code works well.

https://github.com/simolus3/web3dart/blob/a0968df6745214601409e49a261711b778b3e027/lib/src/contracts/types/type.dart#L21

int calculatePadLen(int actualLength) {
      //must be padded with x so that actualLength + x = k * SIZE_UNIT_HEX
      var mod = actualLength % SIZE_UNIT_HEX;
    - return (mod == 0 && actualLength > 0) ? 0 : SIZE_UNIT_HEX - mod;
    + return mod == 0 ? 0 : SIZE_UNIT_HEX - mod;
}

**Comment by simolus3** [comment]
Again, sorry for the long delay. This has also been fixed in [`1.0.0-rc.0`](https://pub.dartlang.org/packages/web3dart/versions/1.0.0-rc.0)
