### ISSUE TITLE
The address.length must be 40

### ISSUE THREAD

**Issue by xiaoch05** [simolus3/web3dart#23]
https://github.com/simolus3/web3dart/blob/a0968df6745214601409e49a261711b778b3e027/lib/src/web3client.dart#L198

Is it should be setted by forcePadLen = 40 ?
String intToHex(dynamic d) => numbers.toHex(d, pad: true, include0x: true, forcePadLen: 40);

e.g.  Send a tx to address "0x0000000000000000000000000000000000000100" cause error.

**Comment by simolus3** [comment]
Sorry for the long delay. This is fixed in [`1.0.0-rc.0`](https://pub.dartlang.org/packages/web3dart/versions/1.0.0-rc.0)
