### ISSUE TITLE
How can i call smart contract functions through web3dart without private key in flutter

### ISSUE THREAD

**Issue by usama1050** [simolus3/web3dart#233]
i have a smart contract with multiple functions that allow user to pay bills in crypto currencies .i just want to known how can i call smart contract functions  through web3dart without private key.I already connect wallet with walletconnect_dart how can i use them instead of private key.

**Comment by simolus3** [comment]
You can implement a custom `Credentials` class delegating the signing operation to `walletconnect_dart` instead.

**Comment by usama1050** [comment]
How? Do you have any example because i didn't get anything in internet.
