### ISSUE TITLE
 Invalid Sender

### ISSUE THREAD

**Issue by VladimirLesunov** [simolus3/web3dart#28]
When I send a transaction, I get an error:
error: {code: -32000, message: invalid sender}

**Comment by VladimirLesunov** [comment]
But getBalance is worked

**Comment by zoechi** [comment]
Related SO question https://stackoverflow.com/questions/54783752/invalid-sender-in-web3dart

**Comment by VladimirLesunov** [comment]
> Related SO question https://stackoverflow.com/questions/54783752/invalid-sender-in-web3dart


but there is no answer)

**Comment by simolus3** [comment]
Interesting. Can you tell me what RPC node you're connecting to (infura, a private geth instance, ...)? It seems like this only fails on some nodes. That error code isn't officially documented, so the exact meaning depends on what node you're connecting to.
Another cause might be a wrong private key. Did you call `getBalance` with the address obtained by calling `Credentials.address` or another?

**Comment by VladimirLesunov** [comment]
I'm connecting to a private RPC, and getting the balance is completely identical to your example.

**Comment by Szkodniq1** [comment]
I'm also getting:
Unhandled Exception: RPCError: got code -32000 with msg "invalid sender".

when trying to send transaction that change the state:
var response = await transaction.send(ethClient);

tried with different chain id, I'm working on private RPC, running on Kaleido geth/poa environment.

Other calls works fine, getBalance and making transactions via call() functions (without changing the state)

**Comment by gavinerasmus** [comment]
I have the same issue. I think it's the chain ID as I had the same problem on MetaMask connecting to my private PoW running on GoolgeCloudPlatform when I had different network and chainIds. Where do I set the chainID / networkID in the web3 client?

**Comment by gavinerasmus** [comment]
I had the same error. I'm running a private chain on google cloud platform. The issue was the chainId and network ID are different as the chainID is hardcoded to 1 in the transaction.dart file. I changed it to a variable that I pass as part of the .send(client, chainId) and it now works. Is this something worth updating in the next version of the package?

**Comment by simolus3** [comment]
Thanks for pointing out the mistake!
The `chainId` can already be changed with the version on master. If you need it now, you can import it with
```yaml
dependencies:
  web3dart:
    git: https://github.com/simolus3/web3dart.git
```
It'll probably take me some time to upload the next version to pub though. To be honest, I'm kind of embarrassed with the quality of this library at the moment so I want to refactor some internal APIs and write more unit tests before I release the next version.
