### ISSUE TITLE
How to connect web3 to ethereum node using flutter?

### ISSUE THREAD

**Issue by ishwarchandratiwari** [simolus3/web3dart#30]
i am getting error while connecting with ethereum node<br>

 - this line ==> print(client.getBlockNumber()); returns error

> E/flutter (22015): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)]
> Unhandled Exception: SocketException: Failed host lookup:
> 'mainnet.infura.io' (OS Error: No address associated with hostname, errno
> = 7)

    import 'package:flutter/material.dart';
    import 'package:http/http.dart';
    import 'package:web3dart/web3dart.dart';
    import 'dart:async';
    const String url =
        'https://mainnet.infura.io/v3/YOUR-PROJECT-ID'; //i have remove YOUR-PROJECT-ID temporarily to post this issue
    class HomeScreen extends StatefulWidget {
      @override
      State<StatefulWidget> createState() {
        return _HomeScreenState();
      }
    }
    
    class _HomeScreenState extends State<HomeScreen> {
      @override
      void initState() {
        main();
        super.initState();
      }
      main() {
        final httpClient =new Client();
        final client =new  Web3Client(url, httpClient);
        print(client.getBlockNumber());
      }
    }

**Comment by simolus3** [comment]
Hi, perhaps the docs are a bit unclear here.
`web3dart` doesn't implement a full Ethereum node itself (it doesn't do mining etc.). Instead, it connects to a third-party Ethereum node to fetch data and to distribute transactions.

It thus needs a URL of a server that implements the [RPC API](https://github.com/ethereum/wiki/wiki/JSON-RPC). You can either host a node yourself (for instance by using [`--rpc`](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options) with geth), or use a public service like [infura](https://infura.io/) which `web3dart` can connect to. If you passed `localhost`, it would try to connect to an Ethereum node running on the same device your flutter app is running on.

If you're getting started, I recommend using a public service like infura so you don't have the hassle of setting everything up yourself. When logging in there and creating a project, it will give you a url that looks like this: `https://mainnet.infura.io/v3/YOUR-PROJECT-ID`. When you pass that url to `web3dart`, it should work. Feel free to re-open if that doesn't work or you have further problems.

**Comment by ishwarchandratiwari** [comment]
i have tried with infura node i am getting same error

**Comment by ishwarchandratiwari** [comment]
@simolus3 Main problem is doc which is not clear , help me writing web3 connection code in flutter , i think i am doing some mistake in writing  web3 connection code

**Comment by simolus3** [comment]
I've just put together this working example: https://gist.github.com/simolus3/b28756ff133f5424b8e9a85ebc16ea2e
I think your problem might be a permission error, see https://github.com/dart-lang/http/issues/185#issuecomment-468806547 for a possible solution

**Comment by ishwarchandratiwari** [comment]
Thanks @simolus3
