### ISSUE TITLE
When will Smart Contract events be supported?

### ISSUE THREAD

**Issue by liuyuejiang** [simolus3/web3dart#34]
It's really awesome to use this plugin, it's very useful, I have learned how to set data to the blockchain and get data from the blockchain. The only problem now is I can listen to the events in the smart contract, I'm just wondering when will this function be supported. Cheers!
Thanks for what you have already done!

**Comment by simolus3** [comment]
A quick update: I got contract events working on the `development` branch, and this is probably what the API is going to look like: https://github.com/simolus3/web3dart/blob/abd873422dccf6422d960fd794ac79e7778d1296/example/contracts.dart#L68-L72

It'll take me some more time to get this ready though - parsing the event data isn't ready yet. Before I'll release this, I also need to do a lot more testing and document breaking api changes.

**Comment by Sach97** [comment]
That's great news, BTW if you need to write types you should use quicktypes.io it has been very helpful for me. P.S.I haven't used your library yet but thank's for your awesome work, I'm keeping an eye on it.

**Comment by simolus3** [comment]
Just published version [`1.0.0-rc.0`](https://pub.dartlang.org/packages/web3dart/versions/1.0.0-rc.0) which implements contract events.
