### ISSUE TITLE
Meta 1.1.7

### ISSUE THREAD

**Issue by gavinerasmus** [simolus3/web3dart#35]
I've upgraded Flutter and Dart and am getting an error:
Because every version of flutter_test from sdk depends on meta 1.1.6 and every version of web3dart from git depends on meta ^1.1.7, flutter_test from sdk is incompatible with web3dart from git.

Is there a way of downgrading the meta dependency in web3dart?
Thanks
G

**Comment by simolus3** [comment]
Lowered the meta dependency to `^1.1.0` on master. I'll publish that version of web3dart as `1.0.0-rc.1` on pub soon.

**Comment by gavinerasmus** [comment]
Thanks
