### ISSUE TITLE
Library should support the websocket rpc API

### ISSUE THREAD

**Issue by simolus3** [simolus3/web3dart#38]
There are nodes, like infura, which don't support some operations like events when not connecting via a websocket. Thus, web3dart should also support the websocket rpc api.
This is what causes #37.

**Comment by liuyuejiang** [comment]
Thank you Simon, how's it going?

**Comment by simolus3** [comment]
Was fixing the coverage tooling yesterday because it didn't work with Dart 2.3. Will take a look at this today. There is a dart library which implements jsonrpc over websockets, so hopefully it should be straightforward to implement.

**Comment by simolus3** [comment]
It's working on `development` now and can be used like this:
https://github.com/simolus3/web3dart/blob/bec10fd91b6b908c9c23eca1df47b727bcc13f85/example/contracts.dart#L58-L60
You'll need to add a dependency on `web_socket_channel: ^1.0.0` in your `pubspec.yaml` and `import 'package:web_socket_channel/io.dart'`. There are errors with ganache when unsubscribing from a stream which I still need to fix, but otherwise everything seems to work.

Also, when using websockets in a Flutter app, you should call `dispose()` on the client when the app goes into background and then create a new `Web3Dart` client when it's resumed. The OS might close the websocket (and therefore, the event streams), so it's better to make that explicit and restore them when the app comes back into foreground.

**Comment by simolus3** [comment]
Got it working, I'll merge it into master and release a new version soon. The previous comment still holds, especially the remarks about `dispose()`. When using infura, be aware that your `wsUrl` is `wss://<NETWORK>.infura.io/ws/v3/YOUR-PROJECT-ID` (note the `/ws/`).
