### ISSUE TITLE
how to convert balance from smart contract to etherUnit

### ISSUE THREAD

**Issue by athlona64** [simolus3/web3dart#42]
final balance = await client.call(
      contract: contract, function: balanceFunction, params: [ownAddress]);
  print('We have ${balance.first} MetaCoins')

**example:** balanceFunction decimal 18 how to convert to ether uint like 18000000000000000000 to 18

**Comment by simolus3** [comment]
You could use something like `var amount = EtherAmount.inWei(balance.first as BigInt)`. To extract the amount in Ether, use `amount.getInEther`. Be aware that this returns an integer and rounds down. You could also use `amount.getValueInUnit(EtherUnit.ether)` to specify other units and get a floating-point result.

**Comment by athlona64** [comment]
> You could use something like `var amount = EtherAmount.inWei(balance.first as BigInt)`. To extract the amount in Ether, use `amount.getInEther`. Be aware that this returns an integer and rounds down. You could also use `amount.getValueInUnit(EtherUnit.ether)` to specify other units and get a floating-point result.

this is work !!
