### ISSUE TITLE
Smart contracts file needs to be updated

### ISSUE THREAD

**Issue by Tolga-GA** [simolus3/web3dart#43]
It seems that the code is changed because I can't use some of the functionalities with the latest update. Please update the file.

**Comment by simolus3** [comment]
Do you mean [this file](https://github.com/simolus3/web3dart/blob/master/example/contracts.dart) as it is on master? It should work with the latest version on pub (`1.0.0-rc2`).

**Comment by Tolga-GA** [comment]
@simolus3 
No it doesn't work.. There has been some changes. See the screenshots below:

![Screen Shot 2019-06-04 at 10 10 40 AM](https://user-images.githubusercontent.com/48081391/58844257-5bdc2c00-86b1-11e9-8b2d-408f640ab976.png)
![Screen Shot 2019-06-04 at 10 11 03 AM](https://user-images.githubusercontent.com/48081391/58844258-5bdc2c00-86b1-11e9-83ac-e35d87149b25.png)
![Screen Shot 2019-06-04 at 10 11 23 AM](https://user-images.githubusercontent.com/48081391/58844259-5c74c280-86b1-11e9-93ab-c54f3eb62e00.png)

**Comment by simolus3** [comment]
Can you check your `pubspec.lock` to verify that you have the latest version of `web3dart`? It should be a release candidate of version `1.0.0`, which [includes that constructor](https://pub.dev/documentation/web3dart/1.0.0-rc.2/credentials/EthereumAddress/EthereumAddress.fromHex.html)

**Comment by Tolga-GA** [comment]
> Can you check your `pubspec.lock` to verify that you have the latest version of `web3dart`? It should be a release candidate of version `1.0.0`, which [includes that constructor](https://pub.dev/documentation/web3dart/1.0.0-rc.2/credentials/EthereumAddress/EthereumAddress.fromHex.html)

You are right, I had to change the version from ^0.4.5 to ^1.0.0-rc.2! Now, it seems that I have to change my code again to make everything work as before. :) I will keep you updated soon, thanks!

**Comment by simolus3** [comment]
Ah yeah sorry, that version has some breaking changes, you can see some recommendations for the migration in the [changelog](https://pub.dev/packages/web3dart/versions/1.0.0-rc.2#-changelog-tab-). I'll update the installing tab later today.

**Comment by simolus3** [comment]
Closing as the original issue is resolved and the installing tab now points to the latest version. If you run into any problems while updating your code, don't hesitate to open another issue :)
