### ISSUE TITLE
How to get every available transactions for a specific ETH address?

### ISSUE THREAD

**Issue by Tolga-GA** [simolus3/web3dart#45]
I was expecting to get a list of transactions by using this library, but it seems that the method doesn't exist. How can I solve this issue without any limitation?

**Comment by simolus3** [comment]
There's not really an efficient way to query for transactions made by an address using the [rpc api](https://github.com/ethereum/wiki/wiki/JSON-RPC), it doesn't provide a method for that. A (very inefficient) workaround exists by
1. taking the amount of transactions sent using `getTransactionCount()`
2. Walking back blocks in the chain and looking at all transactions in there until you find all of those sent from the address.

This library doesn't support loading block information (yet), so it's indeed not possible at the moment by just using this library. I can implement `loadBlockByNumber` and `loadBlockByHash` in this library, but just using that would be very slow.

I know it's a boring answer, but the best approach for your specific question would probably be to build a database of transactions on a server and then perform the query in there: https://cloud.google.com/blog/products/data-analytics/ethereum-bigquery-how-we-built-dataset

**Comment by Tolga-GA** [comment]
@simolus3, I can't thank you enough for the explanation.
