### ISSUE TITLE
How to check if the transaction succeeded

### ISSUE THREAD

**Issue by chart21** [simolus3/web3dart#48]
In the web3js transaction recipt there is a status tag that tells me if the transaction was excecuted successfully. After getting the Transaction information with web3.dart this status tag does not exist. I tested a failing and a not failing transactions (failing transaction reasons: not enough gas, require condition equals false). The problem is I don't see any difference whether a trancsaction fails in the transaction information of web3.dart. Is there a way for me to find out if a transaction succeeded or failed (without events or returns) because the EVM rolled it back?

Edit: Or is there a way to get the transaction recipt with status information (1/0 or true/false) whether the transaction succeeded?

**Comment by simolus3** [comment]
Thanks for the issue. I've implemented the `getTransactionReceipt` on the `development` branch and I'll release a new version later this week.

**Comment by simolus3** [comment]
Published as version `1.1.0` on pub.

**Comment by chart21** [comment]
Thanks a ton for adding the transaciton receipt. Unfortunately it does not seem to work properly:

hash = "0x74836273a74ec6e3a6c939fe0f361c56eeabee03dbacdc41821a8c4ec6dbdbb4";
var transactionInfo = await client.getTransactionByHash(hash); -> works fine 
var transacitonReceipt = await client.getTransactionReceipt(hash); -> Exception has occurred.
FormatException (FormatException: Invalid radix-10 number (at character 1)
10c755

Could't find a way to fix that.

**Comment by Abhimanyu121** [comment]
Is there a way to get transaction receipt via web socket or await getting transaction receipt till the transaction is merged?

**Comment by simolus3** [comment]
I think you need to poll `getTransactionReceipt` until it's valid. You can also use [`.addedBlocks()`](https://pub.dev/documentation/web3dart/2.0.0-dev.9/web3dart/Web3Client/addedBlocks.html) to listen for new blocks and only fetch the receipt after a new block has been added.

**Comment by Abhimanyu121** [comment]
Got it, thanks.
