### ISSUE TITLE
Wallet.fromJson fails when running release apk on Android

### ISSUE THREAD

**Issue by CosimoSguanci** [simolus3/web3dart#49]
When I run the app from Android Studio (both debug and flutter run --release) Wallet.fromJson is working but when I generate the signed apk and then I install it on the device, the right password does not work.

` try {
      Wallet wallet = Wallet.fromJson(walletFile.readAsStringSync(), password);
      return wallet.privateKey;
    } catch (e) {
      print('Error');
      return null;
    }`

I build the apk using:
flutter clean
flutter build apk --release
(the same happens when generating signed apks)

I already tried to switch to beta channel of flutter, but it didn't solve the problem.

The exception is:
`Invalid argument(s): Could not unlock wallet file. You either supplied the wrong password or the file is corrupted`

From some tests I made it seems that the derivedMac generated by fromJson method is different if I run the app using a signed APK.

**Comment by simolus3** [comment]
Did you find a solution?

**Comment by CosimoSguanci** [comment]
Running 'flutter upgrade' seems to have fixed the problem (stable channel). Anyway, this was a really strange behaviour
