### ISSUE TITLE
Mnemonic seed generation | mnemonic backup and import  and other Wallet Standards

### ISSUE THREAD

**Issue by eddywm** [simolus3/web3dart#5]
This is actually not an issue but just a place of following up the progress in implementation of latest  wallets standards in the library.

I have already started with the mnemonic seed generation on my fork and hopefully will get that ready in a week with unit test and co.

**Comment by alvesluc** [comment]
@eddywm How are you doing the mnemonic seed generation with this lib?
I'm having some difficulties after the wallet creation.
