### ISSUE TITLE
Unhandled Exception: RPCError: got code -32601 with msg "The method eth_getBalance does not exist/is not available".

### ISSUE THREAD

**Issue by ahmedmirza994** [simolus3/web3dart#53]
`const String rpcUrl = 'https://api.infura.io/v1/jsonrpc/rinkeby';`
 ` const String privateKey = *************;`

  `final client = Web3Client(rpcUrl, Client(), enableBackgroundIsolate: true);`
  `final credentials = await client.credentialsFromPrivateKey(privateKey);`
  `final address = await credentials.extractAddress();`
  `final etherAmount = await client.getBalance(address);`
  `print(etherAmount.getValueInUnit(EtherUnit.ether));`

when I run this code, this error occurs: 
E/flutter (17927): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: RPCError: got code -32601 with msg "The method eth_getBalance does not exist/is not available".
E/flutter (17927): #0      JsonRPC.call (package:web3dart/json_rpc.dart:49:7)
E/flutter (17927): <asynchronous suspension>
E/flutter (17927): #1      Web3Client._makeRPCCall (package:web3dart/src/core/client.dart:58:35)
E/flutter (17927): <asynchronous suspension>
E/flutter (17927): #2      Web3Client.getBalance (package:web3dart/src/core/client.dart:192:12)

**Comment by simolus3** [comment]
Hi, I think infura stopped responding to non-authenticated requests.

If you create an infura account and setup a project on infura.io, they will give you a project id. Then, try to use `https://rinkeby.infura.io/v3/YOUR-PROJECT-ID` as `rpcUrl`. Does that work for you?

**Comment by ahmedmirza994** [comment]
> Hi, I think infura stopped responding to non-authenticated requests.
> 
> If you create an infura account and setup a project on infura.io, they will give you a project id. Then, try to use `https://rinkeby.infura.io/v3/YOUR-PROJECT-ID` as `rpcUrl`. Does that work for you?

yes its work for me. but now when i send the transaction: 

```
await client.sendTransaction(
    credentials,
    Transaction(
      to: receiverAddress,
      gasPrice: EtherAmount.inWei(BigInt.one),
      maxGas: 10000,
      value: EtherAmount.fromUnitAndValue(EtherUnit.ether, 1),
    ),
    chainId: 42,
    fetchChainIdFromNetworkId: false
  );
```

this error occurs: 
E/flutter (17927): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: RPCError: got code -32000 with msg "invalid sender".
E/flutter (17927): #0      JsonRPC.call (package:web3dart/json_rpc.dart:49:7)
E/flutter (17927): <asynchronous suspension>
E/flutter (17927): #1      Web3Client._makeRPCCall (package:web3dart/src/core/client.dart:58:35)
E/flutter (17927): <asynchronous suspension>
E/flutter (17927): #2      Web3Client.sendTransaction (package:web3dart/src/core/client.dart:262:12)
E/flutter (17927): <asynchronous suspension>

**Comment by Abhimanyu121** [comment]
@ahmedmirza994  try changing chainId, I fixed it by using chainId:3 for ropsten.

**Comment by simolus3** [comment]
Good idea, I think rinkeby uses 4 as its chain id. I'll try it out myself later.
