### ISSUE TITLE
Unhandled Exception: type '_BigIntImpl' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by iceman750** [simolus3/web3dart#55]
I'm getting this error when I call the function balanceOf and set it to double

E/flutter (13715): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '_BigIntImpl' is not a subtype of type 'double'

**Comment by simolus3** [comment]
By calling `balanceOf` you're probably calling a smart contract, right? If that contract returns a `BigInt`, it can't be cast to a double. You could set it to be a `BigInt` and then call [`toDouble`](https://api.dartlang.org/stable/2.4.1/dart-core/BigInt/toDouble.html)

**Comment by iceman750** [comment]
Oh yeah, rookie mistake. Thanks.
