### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by iceman750** [simolus3/web3dart#56]
How to listen to ERC20 transfer events from/to a specific account? 

And is there a way  to wait for a transaction to be mined and then get the status?

**Comment by simolus3** [comment]
> How to listen to ERC20 transfer events from/to a specific account?

You could use `web3dart.events`. The first index declares the event type, the second and third are the respective addresses involved. So if you had a `DeployedContract` in the `myErc20Contract` variable, you could use something like
```dart
final event = myErc20Contract.event('Transfer');

FilterOptions(
  address: myErc20Contract.address,
  topics: [
    [bytesToHex(event.signature, padToEvenLength: true, include0x: true)],
    [bytesToHex(fromAddress.addressBytes, padToEvenLength: true, include0x: true)],
    [bytesToHex(toAddress.addressBytes, padToEvenLength: true, include0x: true)]
  ],
)
```
and then call `web3client.events` with these filter options. If you only want to filter for money sent by an address, just set the third list to null:
```dart
FilterOptions(
  address: myErc20Contract.address,
  topics: [
    [bytesToHex(event.signature, padToEvenLength: true, include0x: true)],
    [bytesToHex(fromAddress.addressBytes, padToEvenLength: true, include0x: true)],
    null,
  ],
)
```

Similarly, if you only want to filter by money received by an address, set the second list to null.

>And is there a way to wait for a transaction to be mined and then get the status?

We don't support that in this library at the moment. I think we could use the [`newHeads`](https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#newheads) pub-sub filter for that, I'll look into it.

**Comment by iceman750** [comment]
Thanks for the info.
I wrote a function that takes the transaction hash and waits for the transaction to be mined. I could share it here with if you want.

**Comment by simolus3** [comment]
Sure, it might be helpful for people stumbling across this.

**Comment by iceman750** [comment]
> Future<void> tellMeHasItMined(String hash) async {
    var transacitonReceipt = await client.getTransactionReceipt(hash);
    while (transacitonReceipt == null) {
           transacitonReceipt = await client.getTransactionReceipt(hash);
    }
    _isPending = false;
    notifyListeners();
  }

This function works with the provider package. It just needs to be called with transaction hash.

**Comment by simolus3** [comment]
Thanks, this is pretty much what people recommend for other Ethereum libraries as well. You might want to add a `await Future.delayed(const Duration(milliseconds: 500))` somewhere in the loop though - otherwise both CPU and data usage could be quite high.

This might also be an alternative, I haven't tried it though
```dart
await client
  .addedBlocks()
  .asyncMap((_) => client.getTransactionReceipt(hash))
  .firstWhere((receipt) => receipt != null)
```

**Comment by YDJSZY** [comment]
How to send a  erc20 token transaction ?

**Comment by iceman750** [comment]
> Thanks, this is pretty much what people recommend for other Ethereum libraries as well. You might want to add a `await Future.delayed(const Duration(milliseconds: 500))` somewhere in the loop though - otherwise both CPU and data usage could be quite high.
> 
> This might also be an alternative, I haven't tried it though
> 
> ```dart
> await client
>   .addedBlocks()
>   .asyncMap((_) => client.getTransactionReceipt(hash))
>   .firstWhere((receipt) => receipt != null)
> ```

Haha yupp I've used it with the web3.js library. Yeah the delay is indeed needed.

The alternative that you provided does it reduce data and CPU usage? and do you think it'll be more efficient than the while loop?

Thanks

**Comment by iceman750** [comment]
> How to send a erc20 token transaction ?

Check out this file: [https://github.com/simolus3/web3dart/blob/master/example/contracts.dart](url)

**Comment by YDJSZY** [comment]
@iceman750 Sorry, it is a little difficult for me to understand your example. can you apply a simple example ? thanks!

**Comment by Rekard0** [comment]
> > How to listen to ERC20 transfer events from/to a specific account?
> 
> You could use `web3dart.events`. The first index declares the event type, the second and third are the respective addresses involved. So if you had a `DeployedContract` in the `myErc20Contract` variable, you could use something like
> 
> ```dart
> final event = myErc20Contract.event('Transfer');
> 
> FilterOptions(
>   address: myErc20Contract.address,
>   topics: [
>     [bytesToHex(event.signature, padToEvenLength: true, include0x: true)],
>     [bytesToHex(fromAddress.addressBytes, padToEvenLength: true, include0x: true)],
>     [bytesToHex(toAddress.addressBytes, padToEvenLength: true, include0x: true)]
>   ],
> )
> ```
> 
> and then call `web3client.events` with these filter options. If you only want to filter for money sent by an address, just set the third list to null:
> 
> ```dart
> FilterOptions(
>   address: myErc20Contract.address,
>   topics: [
>     [bytesToHex(event.signature, padToEvenLength: true, include0x: true)],
>     [bytesToHex(fromAddress.addressBytes, padToEvenLength: true, include0x: true)],
>     null,
>   ],
> )
> ```
> 
> Similarly, if you only want to filter by money received by an address, set the second list to null.
> 
> > And is there a way to wait for a transaction to be mined and then get the status?
> 
> We don't support that in this library at the moment. I think we could use the [`newHeads`](https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#newheads) pub-sub filter for that, I'll look into it.

i tried this example with getLogs() and the filtering did not happen.
if i pass empty topic list , it will get all events emited in the smart contract.
if i pas the event signature, i get the events of that specific event,
if i try to filter some indexed i get nothing,

as topics is List<List<String>>  i assume this example should be like ? :
>   topics: [
>     [bytesToHex(event.signature, padToEvenLength: true, include0x: true),
>     bytesToHex(fromAddress.addressBytes, padToEvenLength: true, include0x: true),
>     null,]
>   ],

if there is somthing i am missing please let me know

**Comment by fangmd** [comment]
Unhandled Exception: JSON-RPC error -32602 (invalid parameters): invalid subscription parameters: data type size mismatch, expected 32 got 20
