### ISSUE TITLE
How to get the nonce ?

### ISSUE THREAD

**Issue by YDJSZY** [simolus3/web3dart#57]
How to get the nonce ?

**Comment by iceman750** [comment]
I think the following code should help you out.

`client.getTransactionCount(address)`

**Comment by YDJSZY** [comment]
Thanks! this is my code:
Future<int> getNonce (address) async {
    return await web3client.getTransactionCount(address, atBlock: BlockNum.pending());
  }
is it ok ?

**Comment by simolus3** [comment]
Yeah that looks alright. Notice that, if you're using `signTransaction` or `sendTransaction` from web3dart, the nonce should be set automatically (we only respect mined transactions for that counter though, maybe that should be changed to `BlockNum.pending()`) as well.
