### ISSUE TITLE
How to get the gas ?

### ISSUE THREAD

**Issue by YDJSZY** [simolus3/web3dart#60]
Now, I can only get the gasPrice, how to get total gas ?

**Comment by simolus3** [comment]
Total gas of _what_? Consumed by a transaction? You could probably use [`TransactionReceipt.gasUsed`](https://pub.dev/documentation/web3dart/latest/web3dart/TransactionReceipt/gasUsed.html)

**Comment by YDJSZY** [comment]
I want to show for user that how total gas he may be need to spent for a transaction.
I found the web.js has a api "web3.eth.estimateGas" and it will return how much gas you maybe need to pay  spent for a transaction

**Comment by simolus3** [comment]
Ah, I see. We don't currently expose that api from web3dart.

**Comment by YDJSZY** [comment]
Thanks. When will you expose the api from web3dart ?

**Comment by YDJSZY** [comment]
This libary help me much work.thank you very much!

**Comment by simolus3** [comment]
Let's keep the issue open to track the progress :)

It shouldn't take long, I'll take a look at it later today.

**Comment by YDJSZY** [comment]
Thank you very much!

**Comment by simolus3** [comment]
I've just released version 1.2.0 which adds the `estimateGas` method to the `Web3Client` interface.

**Comment by SBNTT** [comment]
Hi, is it possible to do the same thing for a smart contract transaction ?

**Comment by simolus3** [comment]
Yes, you could do:
```dart
final transaction = Transaction.callContract(contract: contract, function: yourFunction, parameters: [...]);
await web3client.estimateGas(to: transaction.to, value: transaction.value, data: transaction.data);
```
