### ISSUE TITLE
How to send my ERC20 token to other address?

### ISSUE THREAD

**Issue by zhaobinglong** [simolus3/web3dart#72]

**Comment by simolus3** [comment]
You could use this snippet from the example:
https://github.com/simolus3/web3dart/blob/c4c64910f5743f1b5bfd738438166e795c5ed9aa/example/contracts.dart#L95-L102
Where `sendFunction` is defined here: https://github.com/simolus3/web3dart/blob/c4c64910f5743f1b5bfd738438166e795c5ed9aa/example/contracts.dart#L72
