### ISSUE TITLE
parse hex fail

### ISSUE THREAD

**Issue by Kleak** [simolus3/web3dart#81]
this seems wrong https://github.com/simolus3/web3dart/blob/master/lib/src/crypto/formatting.dart#L59

this transform hex into int but there is not radix here, this lead to parsing error sometime i think

it should be :
```dart
int.parse(strip0x(hex), radix: 16);
```

**Comment by simolus3** [comment]
Oh no, how could I have missed that :astonished:

I'll release the fix to pub soon, thanks for the report.

**Comment by Marcel2508** [comment]
Any Progress on this? When do you plan to publish the fix to pub?

**Comment by simolus3** [comment]
This is included in the current pre-release of `2.0.0.-dev`, which is on pub already.
