### ISSUE TITLE
How to get function result using sendTransaction

### ISSUE THREAD

**Issue by SBNTT** [simolus3/web3dart#84]
```solidity
 function createBallot(bytes32 name, bytes32[] memory proposalNames) public payable returns (uint256) { }
```

```dart
await _client.sendTransaction(_credentials, Transaction.callContract(
  contract: _contract,
  function: _contract.function("createBallot"),
  parameters: [
    StringUtils.stringToByte32(name),
    proposals.map((p) => StringUtils.stringToByte32(p)).toList(),
  ],
  value: EtherAmount.inWei(BigInt.from(CREATE_BALLOT_PRICE)),
  maxGas: 999999,
));
```

How can i get the function result ? (the uint256)
Thankkks !!

**Comment by simolus3** [comment]
I tried to search for a way to implement this, but it seems like this is not possible in Ethereum - there is no way to get the return value of a payable function. If you find a way to do this in another Ethereum library I'd be happy to take a look at how they do it.

A common workaround would be to not make the function return anything. Instead, it could emit an event containing the `uint256` as a field. You could listen for that event using [`events`](https://pub.dev/documentation/web3dart/latest/web3dart/Web3Client/events.html) and decode its data with the [`ContractEvent`](https://pub.dev/documentation/web3dart/latest/contracts/ContractEvent/decodeResults.html) class.
