### ISSUE TITLE
Transaction reciept returns null

### ISSUE THREAD

**Issue by raaj2045** [simolus3/web3dart#85]
Hi, 
I am new to web3dart and flutter. Is this the right way to call the function? 
Because if it is, it is resulting in a transaction error which in-turn returns null as the transaction reciept.

**Code :**

```
var txHash = await ethClient.sendTransaction(
      credentials,
      Transaction.callContract(
        contract: contract,
        function: uploadPost,
        parameters: [
          'New Post content',
          BigInt.from(223),
        ],
        gasPrice: EtherAmount.fromUnitAndValue(
          EtherUnit.gwei,
          BigInt.from(6),
        ),
        maxGas: 1000000,
        from: address,
      ),
      fetchChainIdFromNetworkId: true,
    );

var transactionReceipt = await ethClient.getTransactionReceipt(txHash);
print('Transaction reciept status: ' + transactionReceipt.status.toString()');
```

I am using the rinkeby network. **If I check the txHash on etherscan, it shows tx failed due to contract ran out of gas. But if I call the same contract using it's address on Remix, the transaction does not throw any error and works.**

**Comment by simolus3** [comment]
Are you setting the same gas limit on remix?

**Comment by raaj2045** [comment]
> Are you setting the same gas limit on remix?

Yes I set the same gas limit. 

Interestingly if I add this code after calling the transaction it runs successfully.

'''
await Future.delayed(const Duration(seconds: 20));
'''

I add the delay of 20secs as in Rinkeby 15-20secs is the average time.

**Comment by simolus3** [comment]
> Interestingly if I add delay after calling the transaction it runs successfully.

Yeah that makes sense. I think `getTransactionReceipt` only works if the transaction has been mined, which might take a while.

**Comment by arok** [comment]
Same for me, so maybe it will be better to return nullable type on `getTransactionReceipt` method?

**Comment by simolus3** [comment]
You're right, it should be nullable. I've changed this in this repo, but unfortunately it's technically a breaking change so it requires a major version bump.
