### ISSUE TITLE
Input checks for non-internal methods

### ISSUE THREAD

**Issue by Marcel2508** [simolus3/web3dart#95]
Hi,
this is to catch up on https://github.com/simolus3/web3dart/pull/89#pullrequestreview-389147132. 

When calling ``Transaction.callContract`` with ``parameters`` set to ``null`` it will throw an exception: ``NoSuchMethodError: The getter 'length' was called on null.``. I think there should be some kind of input validation at least for "Public-Interfacing-Methods". Or at least a better way of error reporting, because I'm using a lot of async logic and Isolates, so I for example wont get useful stack traces, which makes error resolving quite hard ;D. 

What do you think about this suggestion?

Thanks
Marcel

**Comment by simolus3** [comment]
Hm, in this case it's marked as `@required` which commonly means that it shouldn't be null.

> async logic and Isolates, so I for example wont get useful stack traces

Not having stack traces sounds horrible for debugging. But isolates should still print a trace with an uncaught error, right?

I've added an `assert(parameters != null)` to the constructor, but if you don't have stack traces I'm not sure how useful that is.
